function scrollToNumber(num, clamp, yPos) {
    return Math.min(num, num - ((yPos - scrollDistance) / yPos) * num).toString().substring(0, clamp).padEnd(clamp, 0)
}
let renderDataAdditions = [
    //Introduction
    {
        type: "text",
        content: () => { return `Part one - Water and Life` },
        fontSize: 60,
        fillColor: "#2169b6ff",
        yPos: positionRefNodes["intro"],
        height: auto,
        leftMargin: 100,
        bottomMargin: 30,
        ref: "SKIP_1",
        anchor: 1
        // scrollLockInterval: [positionRefNodes.intro - 100, positionRefNodes.intro * 2]
    },
    {
        type: "text",
        content: () => { return `  We live in a country where ${scrollToNumber(26.7, 5, positionRefNodes.intro)} million people live without access to clean water devoid of toxins.` },
        fontSize: 30,
        fillColor: "#14122cff",
        yPos: auto,
        height: auto,
        credits: 12,
        leftMargin: 100,
        bottomMargin: 10,

    }, {
        type: "text",
        content: () => { return `  We live in a world where a billions of people - a quarter of humanity - are without access to a basic human right.` },
        fontSize: 30,
        fillColor: "#14122cff",
        yPos: auto,
        height: auto,
        credits: 4,
        leftMargin: 100,
        bottomMargin: 10,
    },
    {
        type: "text",
        content: () => { return `  Yet we've built hundreds of data centers to support the Artificial Intelligence boom. Due to "commercial sensitivity," the true levels of resources these centers consume cannot be substantiated with specificity. But global estimates suggest that around half the yearly water withdrawl of the United Kingdom could be put towards cooling AI data centers by the year 2027. And data centers don't always care where their water or power are coming from. Proximity to population hubs is important for internet-connected applications, So even if those populations are in drought-prone regions of the south and southwest United States the data centers will come.` },
        fontSize: 30,
        fillColor: "#14122cff",
        yPos: auto,
        height: auto,
        credits: 2,
        leftMargin: 100,
        bottomMargin: 10,
    }, {
        type: "text",
        content: () => { return `  These data centers are being located in population centers and cities, bringing jobs lauded as the future. But who will be getting those jobs? Will it be those in need of them? Will the standard of living for all increase around these technological hubs? Undoubtedly not. What jobs will Artificial Intelligence take away? Whose livelihoods will be automated into oblivion? Will minority groups, discriminated against and trapped within a racially oppressive society, have the same access to these new jobs as those who have always been afforded access to the cutting edge in technology? These are important questions, yet ones that are not answered in favor of the allure of Progress.` },
        fontSize: 30,
        fillColor: "#14122cff",
        yPos: auto,
        height: auto,
        credits: 3,
        leftMargin: 100,
    }, {
        type: "text",
        content: "",
        fontSize: 2,
        fillColor: "#25292bff",
        yPos: auto,
        debug: true,
        height: auto,
        leftMargin: 100,
        bottomMargin: 100,

        ref: "endResources"
    },
    // current political analysis
    {
        type: "text",
        content: () => textObjs.power_1,
        fontSize: 30,
        fillColor: "#25292bff",
        yPos: () => { return posRefs.scrst + 5 },
        height: auto,
        leftMargin: 100,
        bottomMargin: 5,
        credits: 4,
        scrollLockInterval() { return [posRefs.endResources - 100, posRefs.endResources + 300] }
    }, {
        type: "text",
        content: () => textObjs.power_2,
        fontSize: 30,
        fillColor: "#25292bff",
        yPos() {
            let a = posRefs.scrst + 403 + 50 + distributeText(textObjs.power_1, screenData.width - 200).length * this.fontSize
            return a
        },
        height: auto,
        leftMargin: 100,
        scrollLockInterval() { let a = distributeText(textObjs.power_1, screenData.width - 200).length * this.fontSize; return [posRefs.endResources + 300 + a, posRefs.endResources + 750] }
    }, {
        type: "text",
        content: () => "Part two - Energy",
        fontSize: 60,
        fillColor: "#006600ff",
        yPos: () => { return posRefs.endResources - 50 },
        height: auto,
        leftMargin: 100,
        bottomMargin: 30,
        ref: "SKIP_2",
        anchor: 2,
        scrollLockInterval: () => { return [posRefs.endResources - 100, posRefs.endResources + 750] }
    }, {
        type: "animObj",
        src: "screenshot",
        xEqn: (screenData.width / 2) - (811 / 2),
        height: 403,
        width: 811,
        credits: 3,
        yPos: () => { return posRefs.endResources + 50 },
        ref: "scrst",
        scrollLockInterval: () => { return [posRefs.endResources - 100, posRefs.endResources + 750] }
    },
    {
        type: "rect",
        fillColor: screenData.fills.highligter,
        height: 20,
        xEqn: () => { return (screenData.width / 2) - (811 / 2) + 655 },
        yPos: () => { return posRefs.endResources + 65 },
        width: () => { return Math.min(Math.max(scrollDistance - posRefs.endResources + 300, 0), 90) },
        scrollLockInterval: () => { return [posRefs.endResources - 100, posRefs.endResources + 750] }
    },
    {
        type: "rect",
        fillColor: screenData.fills.highligter,
        height: 20,
        xEqn: () => { return (screenData.width / 2) - (811 / 2) + 15 },
        yPos: () => { return posRefs.endResources + 95 },
        width: () => { return Math.min(Math.max(scrollDistance - posRefs.endResources + 200, 0), 645) },
        scrollLockInterval: () => { return [posRefs.endResources - 100, posRefs.endResources + 750] }
    },
    // RESOURCES
    {
        type: "text",
        content: () => "Part three - Resources",
        fontSize: 60,
        fillColor: "#25292bff",
        yPos: () => { return posRefs.scrst + 1000 + distributeText(textObjs.power_1).length * 30 + distributeText(textObjs.power_2).length * 30 + distributeText(textObjs.power_1).length * 30 },
        height: auto,
        leftMargin: 100,
        bottomMargin: 30,
        ref: "resStart",
        anchor: 3
    }, {
        type: "text",
        content: () => "The production of an individual phone or laptop, bought once by an individual every few years results in a relatively low amount of resource extraction on a personal level, resulting in little impact either way on how many resources are reaped from the earth and refined in unethical practices created from centuries of colonialism.",
        fontSize: 30,
        fillColor: "#25292bff",
        yPos: auto,
        height: auto,
        leftMargin: 100,
        bottomMargin: 10,
    }, {
        type: "animObj",
        src: "phone",
        xEqn: 100,
        height: 681,
        width: 400,
        yPos: auto,
        debug: true,
        scale: () => { return Math.min(1, Math.max(0.05, (posRefs.resStart - scrollDistance) / screenData.height)) },
    }, {
        type: "text",
        content: () => { return "But what about ten devices?" },
        fontSize: 30,
        fillColor: "#25292bff",
        yPos: auto,
        height: auto,
        leftMargin: 100,
        bottomMargin: 10,
    }, {
        type: "imgArr",
        src: "phone",
        arrWidth: 10,
        arrHeight: 1,
        arrSpacing: 100,
        xEqn: 100,
        height: 681,
        width: 400,
        yPos: auto,
        ySpacing: 0,

        scale: () => {
            return Math.min(1, Math.max(0.05, (posRefs.resStart - scrollDistance) / screenData.height))
        },
    }, {
        type: "text",
        content: () => { return "Or one hundred devices?" },
        fontSize: 30,
        fillColor: "#25292bff",
        yPos: auto,
        debug: true,
        height: auto,
        leftMargin: 100,
        bottomMargin: 10,

    }, {
        type: "imgArr",
        src: "phone",
        arrWidth: 25,
        arrHeight: 4,
        arrSpacing: 100,
        ySpacing: 100,
        xEqn: 100,
        height: 681,
        width: 400,
        yPos: auto,

        scale: () => {
            return Math.min(1, Math.max(0.05, (posRefs.resStart - scrollDistance) / screenData.height))
        },
    }, {
        type: "text",
        content: () => { return "Or thirty thousand?" },
        fontSize: 30,
        fillColor: "#25292bff",
        yPos: auto,
        debug: true,
        height: auto,
        leftMargin: 100,
        credits: 14,
        bottomMargin: 10,
    }, {
        type: "imgArr",
        src: "phone",
        arrWidth: ((screenData.width - 200) / (.025 * 500)),
        arrHeight: 30000 / ((screenData.width - 200) / (.025 * 500)),
        arrSpacing: 100,
        ySpacing: 100,
        xEqn: 100,
        height: 681,
        width: 400,
        bottomMargin: 10,
        yPos: auto,
        debug: true,
        scale: () => { return Math.min(1, Math.max(0.025, (posRefs.resStart + 100 - scrollDistance) / screenData.height)) },
    }, {
        type: "text",
        content: () => { return "  That's the kind of number that shapes an industry. And 30,000 is only a 2023 estimate of the number of GPUs (Graphics Processing Units - a component critical to training and running AI models) that the company NVIDIA would sell to OpenAI (just one AI company!) for an early version of ChatGPT. (Just one of their products! Image and video generation take a world more of processing power, and modern AI models are integrated into so many more facets of daily life.)" },
        fontSize: 30,
        fillColor: "#25292bff",
        yPos: auto,
        height: auto,
        credits: 13,
        leftMargin: 100,
        bottomMargin: 10,
    }, {
        type: "text",
        content: () => { return "  30,000 chips comes from a figure much closer to the beginning of the AI boom. The number of chips and computing units manufactured for AI has skyrocketed past it, to the point where NVIDIA has become one of the world's highest-valued companies, in the trillions of dollars, at times surpassing both Apple and Microsoft." },
        fontSize: 30,
        fillColor: "#25292bff",
        yPos: auto,
        height: auto,
        leftMargin: 100,
        credits: 13,
        bottomMargin: 10,
    }, {
        type: "text",
        content: () => { return "  Along with the disastrous outcome of an increase in mining of heavy metals, the state of landfills (especially those holding hazardous waste) in the United States disproportionately impacts people of color. A substantial increase in E-waste as GPU clusters fail will correlate with an increase in corporate waste and toxins dumped into these locations, and further the harms done to vulnerable populations." },
        fontSize: 30,
        fillColor: "#25292bff",
        yPos: auto,
        height: auto,
        credits: 8,
        leftMargin: 100,
        bottomMargin: 10,
    }, {
        type: "text",
        content: () => { return "  The indirect impacts of the generative AI market's growth are widespread, exacerbating preexisting harms and, dangerously, damaging corporations' and governments' incentives to address those harms." },
        fontSize: 30,
        fillColor: "#25292bff",
        yPos: auto,
        height: auto,
        leftMargin: 100,
        bottomMargin: 100,
    }, {
        type: "text",
        content: "Part 4 - Informational colonialism",
        fontSize: 60,
        fillColor: "#a75600ff",
        yPos: auto,
        leftMargin: 100,
        ref: "SKIP_4",
        height: auto,
        bottomMargin: 10,
        anchor: 4
    }, {
        type: "text",
        content: "  The internet is the vastest single sink of human knowledge in the history of the world. An inspiring thought, is that not? The millions of thinkers and writers and artists who have developed their craft in the cyberspace? This is perhaps a romanticization of the matter. But it is true that a lot of very human things have happened because of the internet and the connection it brings. Not all good things, not all bad things. But overwhelmingly, human things.",
        fontSize: 30,
        fillColor: "#3b2610ff",
        yPos: auto,
        bottomMargin: 10,
        leftMargin: 100,
        height: auto,
    }, {
        type: "text",
        content: "  When we look at the settler colonialism of the Americas we see land, a sacred, communal thing, taken and treated like unowned property, fresh for the taking, becoming free capital and speeding America on its way to a powerful economy.",
        fontSize: 30,
        fillColor: "#3b2610ff",
        yPos: auto,
        leftMargin: 100,
        bottomMargin: 10,
        height: auto,
    }, {
        type: "text",
        content: "  What interesting parallels, then, the rise of Artificial Intelligence demonstrates. With hundreds of gigabytes of human thought and creation and culture scraped mercilessly without consulation or payment a public good, accessible to everyone, becomes stolen and regurgitated into a service that then begins to destroy the very thing that gave it life.",
        fontSize: 30,
        fillColor: "#3b2610ff",
        yPos: auto,
        leftMargin: 100,
        bottomMargin: 10,
        height: auto,
    }, {
        type: "text",
        content: "  This ex of course on a wholly separate scale from the events that led to the genocide of millions that was perpetrated by European colonialism. But it speaks to the tendencies of a capitalist society that, even in what is lauded as the future, cultures and human expression are stolen and generalized away from uniqueness for the sake of profit and power for the elite. It's important to note that groups whose cultures are already traditionally underrepresented in digital spaces will see this problem exacerbated as AI reduces the most-visible online parts of their culture to whatever incomplete notions of those cultures were fed into its maw. All this in the name of Efficiency. In the name of Progress. In the name of Advancement. ",
        fontSize: 30,
        fillColor: "#3b2610ff",
        yPos: auto,
        leftMargin: 100,
        bottomMargin: 100,
        height: auto,
    },
    // PART THE FIFTH
    {
        type: "text",
        content: "Part 5 - Social impacts",
        fontSize: 60,
        fillColor: "#a75600ff",
        bottomMargin: 10,
        yPos: auto,
        leftMargin: 100,
        ref: "SKIP_5",
        height: auto,
        anchor: 5
    }, {
        type: "text",
        content: "  How easy is it to make something up?",
        fontSize: 30,
        fillColor: "#3b2610ff",
        yPos: auto,
        leftMargin: 100,
        height: auto,
    }, {
        type: "text",
        content: "  If you wanted to, how easy would it be to write an essay casting skepticism on the fact that climate change is real, or one that claims there 'isn't enough evidence' to link racial segregation with statistically poorer health outcomes?",
        fontSize: 30,
        fillColor: "#3b2610ff",
        yPos: auto,
        leftMargin: 100,
        height: auto,
    }, {
        type: "text",
        content: "  Not hard. Perhaps. But how long would this take? How many hours or days would it take to write many of those articles, scattered across the internet, having them cite each other (or other, made up sources) for an air of authenticity?",
        fontSize: 30,
        fillColor: "#3b2610ff",
        yPos: auto,
        leftMargin: 100,
        height: auto,
    }, {
        type: "text",
        content: `  How easy would it be to make an average person read every single one of those essays and, with only a cursory glance at their content, think "well, that looks like a decently written-out essay"?`,
        fontSize: 30,
        fillColor: "#3b2610ff",
        yPos: auto,
        leftMargin: 100,
        height: auto,
    }, {
        type: "text",
        content: `  Imagine that that work could be done with a few keystrokes, and propogated across the internet with only a minimal need for a human agency?`,
        fontSize: 30,
        fillColor: "#3b2610ff",
        yPos: auto,
        leftMargin: 100,
        bottomMargin: 20,
        height: auto,
    }, {
        type: "text",
        content: `  That's a first threat brought by Artificial Intelligence - its confidence, its ease of use, its ubiquity. How easy it has now become for malicious actors to spread this sort of content.`,
        fontSize: 30,
        fillColor: "#3b2610ff",
        yPos: auto,
        leftMargin: 100,
        height: auto,
    }, {
        type: "text",
        content: `  But the second threat is perhaps even more concerning.`,
        fontSize: 30,
        fillColor: "#3b2610ff",
        yPos: auto,
        leftMargin: 100,
        height: auto,
    }, {
        type: "text",
        content: `  What's the first thing you need to address global, existential problems like Climate Change and Climate Justice? You need resources, yes. You need information and a platform and something to amplify your voice. But before all of that you need people.`,
        fontSize: 30,
        fillColor: "#3b2610ff",
        yPos: auto,
        leftMargin: 100,
        height: auto,
    }, {
        type: "text",
        content: `  People with the ability to problem-solve and think critically. Not many perhaps at first, but in time lots of them.`,
        fontSize: 30,
        fillColor: "#3b2610ff",
        yPos: auto,
        leftMargin: 100,
        bottomMargin: 20,
        height: auto,
    }, {
        type: "text",
        content: () => { return ` So what ${scrollDistance - posRefs.sWdWd > -400 ? "CAN" : "do"} we do` },
        fontSize: 30,
        fillColor: "#291d0fff",
        yPos: auto,
        leftMargin: 100,
        bottomMargin: 20,
        height: auto,
        ref: "sWdWd"
    }, {
        type: "text",
        content: ` If those people`,
        fontSize: 30,
        fillColor: "#7e6e5aff",
        yPos: auto,
        leftMargin: 100,
        bottomMargin: 20,
        height: auto,
    }, {
        type: "text",
        content: ` Become few and far between?`,
        fontSize: 30,
        fillColor: "#b9aea4ff",
        yPos: auto,
        leftMargin: 100, bottomMargin: 20,
        height: auto,
    }, {
        type: "rect",
        xEqn: 107,
        yPos: () => { return posRefs.sWdWd - 20 },
        doNotResetAuto: true,
        fillColor: "#291d0fff",
        width: () => {
            let a = render.measureText(` So what ${scrollDistance - posRefs.sWdWd > -400 ? "CAN" : "do"} we do`).width
            return Math.min(Math.max(a - (posRefs.sWdWd - scrollDistance - screenData.height / 2) / 2, 0), a)
        },
        height: 5,
    }, {
        type: "text",
        content: `  We're still in the early days of the rise of Artificial Intelligence. But as it stands, dependence on AI to write, learn and develop thoughts has been demonstrated to have an adverse impact on peoples' abilities to think critically and produce novel, innovative solutions. This is a problem among adults, but could be impacting children and teens in ways that are only now beginning to show their faces. In a world where a striking majority of students use AI, how many of them will be well-equipped to tackle the future in novel ways?`,
        fontSize: 30,
        fillColor: "#3b2610ff",
        credits: 14,
        yPos: auto,
        leftMargin: 100, bottomMargin: 20,
        height: auto,
    }, {
        type: "text",
        content: `  Because AI models do not look towards the future, they are trained on the past. And "solutions" they offer to the climate crisis are often protective of the status quo that they were trained on, not wanting to upset anyone with radical solutions.`,
        credits: 10,
        fontSize: 30,
        fillColor: "#3b2610ff",
        yPos: auto,
        leftMargin: 100, bottomMargin: 20,
        height: auto,
    }, {
        type: "text",
        content: `  But it is those radical solutions that we will need in order to address and solve injustices around the world. The fewer of them we can produce (and, just as importantly, the fewer of them we can get the world at large to understand), the less progress we will be able to make towards addressing those injustices.`,
        fontSize: 30,
        fillColor: "#3b2610ff",
        yPos: auto,
        leftMargin: 100, bottomMargin: 100,
        height: auto,
    }, {
        type: "text",
        content: `Generative Artificial Intelligence is an existential threat to humanity. It has the power to do so many things, yet its outcomes harm the environment, further injustices of so many kinds, are a harm to culture, and weaken our ability to weather change.`,
        fontSize: 40,
        fillColor: "#3b2610ff",
        yPos: auto,
        leftMargin: "centerText",
        bottomMargin: 20,
        height: auto,
    }
]
let textObjs = {
    power_1: "This increase in water usage coincides with a rise in investment in fossil fuels and lowering of regulatory power in the United States' federal government. President Trump's Executive Order 14241 specifically mentions “Emerging technologies” as an impetus for increasing domestic energy production (“including coal”). This is no coincidence. The power consumption requirements of AI data centers at scale have outpaced the rate of growth in sustainable energy. This has slowed the green energy transition, keeping coal plants open as power needs balloon. The order also specifies how coal can be used 'in any weather condition' - no unimportant point: data centers generally support services with near-constant demand, substantially increasing their total power draw. It is also no coincidence that many companies have reported increases in their net emissions and begun to roll back their once-ambitious climate goals. It is these goals that would restrict their access to the explosive growth and profits in the lucrative generative AI market.",
    power_2: "This will increase the environmental burden on margianalized communities, furthering the impact of fossil fuels on the people who can least afford it."
}